[package]
name = "s4"
description = "Simpler Simple Storage Service: highlevel API extensions for Rusoto's S3Client"
version = "0.0.6"
documentation = "https://docs.rs/s4"
repository = "https://gitlab.com/pgerber/s4"
authors = ["Peter Gerber <peter@arbitrary.ch>"]
license = "LGPL-3.0+"
readme = "README.md"
keywords = ["AWS", "S3"]

[badges]
gitlab = { repository = "pgerber/s4" }

[dependencies]
derive-error = "0.0"
log = "0.4"
fallible-iterator = "0.1"
futures = "0.1"
rusoto_core = "0.33"
rusoto_credential = "0.12"
rusoto_s3 = "0.33"
tokio-io = "0.1"

[dev-dependencies]
tempdir = "0.3"
rand = "0.4"
env_logger = "0.5"
quickcheck = "0.6"
