name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: rustup update
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
    - name: Build
      run: cargo build --verbose
    - name: Start minio
      run: |
            docker pull minio/minio && docker run -d --rm -p 9000:9000 --env "MINIO_ACCESS_KEY=ANTN35UAENTS5UIAEATD" \
            --env "MINIO_SECRET_KEY=TtnuieannGt2rGuie2t8Tt7urarg5nauedRndrur" \
            --env MINIO_DOMAIN=localhost minio/minio server /minio
    - name: Run tests
      run: cargo test --verbose
    - name: spin down minio
      run: |
        docker stop `docker ps -a | awk '/minio/ {print $1}'`
        docker rm `docker ps -a | awk '/minio/ {print $1}'`
