name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  services:
    image: docker://minio/minio:latest
    ports: 9000:9000
    env:
      - MINIO_ACCESS_KEY: ANTN35UAENTS5UIAEATD
      - MINIO_SECRET_KEY: TtnuieannGt2rGuie2t8Tt7urarg5nauedRndrur
      - MINIO_DOMAIN: localhost

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: rustup update
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: spin down minio
      run: docker rm `docker ps -a | awk '/minio/ {print $1}'`
